### ISSUE TITLE
Error in ask deploy

### ISSUE THREAD

**Issue by mcarlosro** [alexa/alexa-heroku-help-desk-sample#1]
Following the steps and in part 3, I got the following error:

$ ask deploy
-------------------- Create Skill Project --------------------
Profile for the deployment: [default]
Skill Id: amzn1.ask.skill.bc0401e1-7fa8-4310-b3cc-b5444f4139a2
Skill deployment finished.
Call update-model error.
Error code: 400
{
  "message": "Interaction model is not valid.",
  "violations": [
    {
      "message": "InvalidSlotTypeName: Slot type name \"AMAZON.SearchQuery\" is invalid. The name of a custom slot type must begin with an alphabetic character and can consist only of alphabetic characters or underscores."
    }
  ]
}

**Comment by ericchenmou** [comment]
Thanks for reporting this - the commit I just made should resolve the issue but please let us know if you see any other errors.
